# Generated by Django 4.1.7 on 2023-04-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_reacttocomment_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReactToComment',
        ),
    ]
