# Generated by Django 4.1.7 on 2023-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_slug_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default=1, upload_to='profile_photos/%Y/%m/%d/', verbose_name='Фото пользователя'),
            preserve_default=False,
        ),
    ]
